# Generated by Django 4.2.7 on 2026-01-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
